### ISSUE TITLE
Fallback mappings not applied

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#144]
Repro: remove the matching map for a device in-hand from the SDL DB that has a mapping in the YYG db, or on a platform that auto-assigns a mapping if none is found. Mapping fallback fails. Tested on Android and Windows.

https://github.com/JujuAdams/Input/blob/774cc8b4263f441786590d558bd81eda7b55480b/scripts/__input_gamepad_set_mapping/__input_gamepad_set_mapping.gml#L418

Should happen here (see trace message), but isn't. Expected behavior is for the default-assigned map to be cached on device connect and then applied in absence of a custom remapping.. but that functionality doesn't appear to be authored.

**Comment by JujuAdams** [comment]
To be clear, by "default-assigned" you mean assigned by GameMaker yep?

If that's the case, we're only clearing out GameMaker's mapping when the `.set_mapping()` method is called for a gamepad instance. If there's no SDL definition, `.set_mapping()` isn't called so we never touch GameMaker's mapping system.

Additionally, `custom_mapping` is set to `true` when `.set_mapping()` is called. When this flag is `true` it switches the gamepad button/axis checkers from returning native functions to our own state-tracking system. `custom_mapping` defaults to `false`, ensuring that we return the GameMaker-ordained values instead of our own, unless SDL succeeds (and `.set_mapping()` is called).

Sooo... I think no changes are necessary? I think? Lemme know if this isn't what's desirable

**Comment by offalynne** [comment]
working as intended
