### ISSUE TITLE
SDL gamepad 'touchpad' field

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#194]
Currently we deliberately omit support for the PS4/PS5 touchpad button besides on the PlayStation platform target. This is a result of GM lacking a constant reference (mapping to `gp_select` on console), and SDL handling it as a special case: omitting the `touchpad` field from the mapping DB on all supported platforms (except iOS) and applying it explicitly upon gamepad type identification.

We can add wider support for the touchpad button itself and formalize the gamepad constant in a similar way to SDL, if desirable.

Upsides:
- One more bindable button on supported platforms (desktop, mobile, web)
- Consistent explicit cross-platform binding of touchpad button with constant (eg. `gp_touchpad`)

Downsides:
- Binding is invalid for non-PlayStation 4/5 type controllers
- Conflicts with GM docs (note that we already conflict on `gp_guide` and `gp_select`)
- Creates requirement for mapping explicitly on PlayStation platform targets instead of `gp_select` falling back (mitigable)
- Creates potential for double-input on Linux  and Android targets which ship mouse drivers for the touchpad (mitigable)
- Extra work: should we bother binding the button where touch input isn't supported?

**Comment by FaultyFunctions** [comment]
I don't really think this is necessary tbh. Creates more downsides/complexity than upsides.

As someone who has used the DS4 controller on PC as my main controller and now the Dualsense, I kinda just expect the touchpad to do nothing on PC games.

While I suppose it would be nice to have, if it makes bindings for the touchpad finicky on the dev's end depending on platform, I don't think it's worth it in the end.

**Comment by tabularelf** [comment]
Not worth it frankly. I don't even consider touchpads being a possibility when it comes to adding in support for gamepads. Because usually they just have joysticks and buttons. No fancy touchpad. Having multiple downsides for it on top with little to no benefit just shows that it's a waste of time and effort for everyone to have.

I'm also not a huge fan of supporting heavy exclusive features. It's nice sure, but it's not really mainstream across gamepads afaik.
