### ISSUE TITLE
Add input_binding_is_valid()

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#200]
`input_binding_is_valid(binding, player = 0)`

Returns true/false indicating whether the given player (defaulting to 0 if unspecified) is able to use the given binding. The device that this funciton checks against is determined firstly by the type of binding (keyboard/mouse/gamepad) and secondarily by hardware-specific limitations. In the case of gamepads this is simply what buttons/axes are available. In the case of keyboards, what inputs are available is determined as much by per-platform quirks as what keys are on the keyboard.

At any rate, this function will allow for dev-side confirmation of what bindings are reasonable for players. This functionality already exists implicitly in the binding system so exposing it to the dev will allow for more flexible (custom) binding systems to be written for less common use cases.

**Comment by offalynne** [comment]
keyboard key validity: greater than 7, less than 255 (utf8), not blocked
gamepad button/axis validity: gamepad slot nonempty, gamepad not blocked, specified field found in map, or device unmappd

**Comment by offalynne** [comment]
#260

**Comment by offalynne** [comment]
Based on recollection of some of our conversation and 

> This functionality already exists implicitly in the binding system so exposing it to the dev will allow for more flexible (custom) binding systems to be written for less common use cases.

I suspect you may have wanted this to just be a refactor of the existing checks for use both by the binding system internals and a 'validity check' interface, however checking set values and filtering incoming input for binding doesn't quite work out the same unfortunately -- checking platform allowance, ignored keys, and mapped gamepad inputs for example are the same, but other cases differ.

For example we don't need to filter keys that aren't available on a particular platform (since they can't be user bound anyway), but should consider them invalid when checked. We don't need to validate a gamepad mapping when binding (obviously it worked if it's bound), but we should validate the same when checking explicitly, in case the library user or mapping system produces a binding that is invalid for a given gamepad device.

**Comment by JujuAdams** [comment]
Accepted PR https://github.com/JujuAdams/Input/pull/260
