### ISSUE TITLE
Check out iOS

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#44]
issue as discussed. compatible pads: https://github.com/libsdl-org/SDL/blob/main/src/joystick/SDL_gamecontrollerdb.h#L839-L855
any compatible pad should be normalized and doesn't need mapping, through it may be possible to infer type by description.

**Comment by offalynne** [comment]
All clear on web, gotta set up app pipeline to test native. Away from my Mac kit for a couple weeks.

**Comment by JujuAdams** [comment]
I've got iOS set up for testing native so I'll have a poke today. I'll be able to test with PS4 + XB1 wireless which looks like it'll be good enough? Can rummage up a proper MFI gamepad from a friend if needed

**Comment by JujuAdams** [comment]
Needed to fix up iOS a bit (https://github.com/JujuAdams/Input/commit/9fd7591fe3719a2d044dfde773f79e3b2d6294f8 and https://github.com/JujuAdams/Input/commit/932d579668c0d95c4e5b87de36a3e8261530cfd5) but it otherwise handles my PS4 + XB1 controllers fully

I did notice that  `gp_select` is a little weird on iOS. If you hold it down it'll take a screenshot whereas if you tap it then the game will detect a short press for a few frames _after_ the button is released. I suppose that makes sense but... unexpected.

Keyboard input via Safari looks workable. Basic key input is ok with a couple quirks - capslock is a toggle rather than momentary like everything else (including numlock!), we don't get F1-4 or F7-12 as they're used for system-level controls (brightness etc.). Arrow keys return as keys and not gamepad buttons (hooray!)

Keyboard input via native is an absolute no-go, see #138. I doubt this'll ever get fixed unless there's a strong usecase that a professional developer can demonstrate

**Comment by offalynne** [comment]
> we don't get F1-4 or F7-12 as they're used for system-level controls

👍

> capslock

ignored, should be good

can you confirm the weird select behaviour on xbox pad, or is the “Share” issue PlayStation only ?

**Comment by JujuAdams** [comment]
iirc both, will re-test.

**Comment by JujuAdams** [comment]
Yep, happens with XB1 controller as well.

**Comment by offalynne** [comment]
Looks like it’s an OS setting https://www.reddit.com/r/iosgaming/comments/hxg0ki/comment/g2e9304/

**Comment by JujuAdams** [comment]
Neat. We should document that option but otherwise I think we're good to go for iOS
