### ISSUE TITLE
Documentation improvement -- better examples, hints?

### ISSUE THREAD

**Issue by pdseventyeight** [offalynne/Input#472]
Would it be possible to improve the documentation at https://www.jujuadams.com/Input/#/5.1/ ?

**I don't know how to create a pull request** -- when I clicked the corresponding button, it wanted me to do things I have no idea how to do. I'm used to submitting such requests/reports/proposals via forums.

I'm struggling with configuring Input5 to do what I want it to do, and I can't figure it out from the documentation.

In a "Newbie tutorial", I would expect - and that's what I'm proposing - a TUTORIAL approach:

Tell them what you're about to teach them.
Then tell them what to do.
Then let them see what it DOES.
Then explain WHY it DOES it: how does each thing they did connect with what it does.
Then build on top of that with the next step.

**At the very least, the Newbie section should feature:**

- Binding several different inputs to the same verb ("shoot").
- Checking for the input to determine if we should be "shoot"ing.
- checking for a DOUBLE CLICK/DOUBLE TAP to achieve a different action using the SAME input (Something like "Double Tapping the shoot input will instead lob a grenade").
- Resolving the issue that when you double tap, it first shoots and THEN lobs a grenade -- how do I prevent the single shot when double tapping? 
- When and how to use "input_consume"

*** 

As I'm trying to slowly figure it out, I've come across this: The manual for verb groups gives this 'template':

INPUT_VERB_GROUPS = {
    \<group name\>: [\<verb1\>, \<verb2\>, ...],
    \<group name\>: [\<verb3\>, \<verb4\>, ...],
    ...
}

However, the \<verb1\>, \<verb2\> part is misleading -- those have to be STRINGS ("verb1", "verb2"), while in the profile definition, those are struct variables.

***

Beyond that, I think the scripts for configuring Input5 could use a bit more explanation or hints -- hints such as 
"If you increase the value of INPUT_REPEAT_DEFAULT_PREDELAY, the effect will be that if the player holds that input down, there will be a more pronounced delay after the first instance of the action before it starts repeating" or "If you plan to use both long-press and double-press of the same input, then INPUT_LONG_DELAY should always be {? shorter/longer ?} than INPUT_DOUBLE_DELAY".

The overarching 'issue' - forgive me for using that word - is that Input5 is, at this point in time, a complex system spread across ~100 script files, with huge number of macroes and other configuration mechanisms, and if a developer of a game runs into a problem while using it, they don't even know where to start looking for a solution. A section such as "Frequently encountered problems and their likely causes" might be helpful as well.

**Comment by offalynne** [comment]
The general problem, that Input is large, difficult for you to understand, and there are specific parts of it that are confusing, may be worth addressing.

Unfortunately complaints alone are not helpful in this case — we have done our best to make documentation and comments clear, beyond that we require help to make improvements.

Input is an open project and you are able to contribute. Since you do not know how to make a pull request, I suggest reading in order to learn how to do so. There are many guides and examples for this (for example, [first-contributions](https://github.com/firstcontributions/first-contributions/blob/main/README.md)), hopefully you might find one that suits your needs.

If you want to contribute only via suggestion, please suggest the exact edits you are proposing, instead of providing examples of things you don’t like.

As for your individual points, here are some answers.

> Tell them…
> Teach them…
> Then let them…
> Then explain…
> Then build…

Feel free to revise the language or steps in the tutorial to your liking, making changes or adding the things you feel are missing, and we will be glad to credit you for the contribution upon review.

> Checking for the input

The tutorial includes this, please read closely.

> Binding several different inputs…
> DOUBLE CLICK/DOUBLE TAP…
> how to use "input_consume"…

These are outside the scope of a quick tutorial and are thoroughly documented where relevant — we do not think they belong in the tutorial.

> those have to be STRINGS ("verb1", "verb2"), while in the profile definition, those are struct variables

Verbs and bindings are different types. If this is confusing or incorrectly explained, please let us know where, and propose an edit.

> Input5 is, at this point in time, a complex system

Correct

> if a developer of a game runs into a problem while using it, they don't even know where to start looking for a solution

I disagree. The place to look is the documentation. If the documentation is inadequate, [you can ask on Discord](https://discord.gg/8krYCqr), linked from the project and documentation, where many of the library’s contributors and users would be glad to help you and improve the library and the documentation in follow up, if appropriate.

> A section such as "Frequently encountered problems and their likely causes"

We help people every day with their questions about the library, and address common issues by either improving the project or improving the documentation until the issue is no longer “frequent”. A list of easily answered questions is a band-aid necessary if such issues persist unaddressed, which (for now) is not the case.

If you disagree, feel free to draft a list of these problems and their solutions and we would be glad to consider adding it to the documentation.
