### ISSUE TITLE
High percentage of a single step

### ISSUE THREAD

**Issue by castorpollux285** [offalynne/Input#756]
Hello,

I use Input 6. When I debug my game, input_controller_object_Step_1 call takes about 44% of a single step. 

Seems pretty high to me. Is this a normal behaviour?

Thanks in advance!

<img width="788" alt="Bildschirmfoto 2023-08-05 um 17 39 01" src="https://github.com/JujuAdams/Input/assets/24854105/641c1e7b-8ba4-42c2-856d-1efe550a5b2e">

**Comment by offalynne** [comment]
Always examine **Time (Ms)** and ignore **Step (%)**.  Do not rely on **Step (%)** for diagnosing or reporting performance issues.

> *44% of a single step*

If you put Input in an otherwise empty project, it will show 100%!

Input is a lot of GML, and GML is slow. Input does a lot of work, and we think 0.175 Ms is acceptable. If you do not, there is a very good chance your project does not require the library !
