### ISSUE TITLE
No way to set gamepad axis thresholds for binding scan(?)

### ISSUE THREAD

**Issue by EthGaming101** [offalynne/Input#879]
I'd like to be able to have axis thresholds set using `input_axis_threshold_set` apply to the binding scan functions, unless there's already a built-in system for joystick sensitivity when scanning. For reference, I am using a standard PS4 controller, and usage of the binding scan feature is hindered by the right joystick seeming drifting left.

**Comment by offalynne** [comment]
Check out `INPUT_DEFAULT_AXIS_MIN_THRESHOLD` config

**Comment by offalynne** [comment]
Does look like scanning should be respecting axis thresholds: https://github.com/offalynne/Input/blob/7cdbb10acd8391b730aa416f93a6d33041bd902a/scripts/__input_class_source/__input_class_source.gml#L293

Binding should (maybe) be using axis delta instead of checking raw as hotswap presently does, I will have a further look into it. 

If your gamepad is drifting more than 1/3 of the axis range that's going to be quite problematic regardless. You can calibrate your thumbstick axes with the Windows game controller dialogue to get better system wide behaviour out of the device.

**Comment by EthGaming101** [comment]
I may have exaggerated the severity of the joysticks: both joysticks are neutral to the point the deviancy is only beyond the first decimal digit. I've also made sure DS4Windows is off, and through gamepad testers there isn't any other input coming from any other devices other than the PS4 controller.

I've also tried raising `INPUT_DEFAULT_AXIS_MIN_THRESHOLD`, and that doesn't seem to be doing anything.

**Comment by offalynne** [comment]
You're going to have to dig into the debugger and figure out what's going on I'm afraid as your issue is not reproducible. If you download the GitHub project there are example objects available for you to test with. If you want to document your issue more specifically feel free, until then not much I can help you with.

**Comment by EthGaming101** [comment]
I managed to find the solution! I was a little naive, since it was another virtual joystick, vJoy, that was causing the issues. Disabling it in device manager solved it: sorry for the trouble.
