### ISSUE TITLE
`input_player_get_gamepad` returning -1 when player is confirmed to have sources and be using gamepad... roughly half the time.

### ISSUE THREAD

**Issue by ABNTGeneric** [offalynne/Input#889]
![InputConnectionIssue03](https://github.com/user-attachments/assets/6a18a740-d097-4e57-b2ec-da510527a9e9)
I'm simply plugging in and unplugging gamepad 0 and the getter functions for reading what's connected to player 0 are inconsistent with each other.

`input_sources_get_array` tells me that player 0 is connected to gamepad 0, and `input_player_using_gamepad` also checks out, but `input_player_get_gamepad` still returns -1.

But the horror is that this only happens about half the time I plug the controller back in. It seems totally random, and I've gotten streaks of 3-4 re-connections that work successfully until one just simply doesn't. No other code in my game is running, just this menu and the appropriate methods that are called after the "gamepad discovered" async event triggers.

I suppose for this issue I can add another block of code to check if `input_player_get_gamepad >= 0` but what happens if it isn't? How else do I get the gamepad index the player is using save for the sources array? And what data type are the elements of that array? Clearly not integers, which is what I need.

Why is all of this information updated separately? Why is it not just a single data structure? Should it really be necessary to cross reference a bunch of different getter functions just to get an accurate idea of what's connected to who?

**Comment by ABNTGeneric** [comment]
For anyone having the same issue, it seems necessary to allow the library _at least_ two frames to update all of the return values for these functions. You can't be running code like the example above directly from the async_event because it may take place in-between whatever methods the library uses to update each of these functions. I suggest running your game in a state machine and transitioning to a buffer state for one frame, then running a state that purely triggers the methods your objects use to update their gamepad info, then finally returning to the game's normal state. Using this technique, I've avoided the crash above.

**Comment by offalynne** [comment]
The library is just GML. If you are this deep in the weeds, please use the debugger to find the problem, or at least clearly articulate your use so we can come to a satisfactory solution.

> async_event

When relying on some combination of library and non-library methods this is inevitable. Input does not use aysnc events. Your discrepancy is GM awaiting the next frame to register the gamepad after the initial async event.

If you are using your own gamepad assignment instead of Input's (see Multiplayer Guide), you are going to need some rigor to get this done.

> Why is all of this information updated separately

It is not updated separately, it is different information. As explained in the other issue you opened and then closed yourself, they are semantically different. `input_player_get_gamepad()` does gamepad connection evaluation, `input_sources_get_array()` and `input_player_using_gamepad()` do not.
